# Generated by Django 5.0 on 2024-03-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adul", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hazardprofile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Facility_classification_large",
                    models.TextField(blank=True, db_column="시설물분류(대)", null=True),
                ),
                (
                    "Facility_classification_medium",
                    models.TextField(blank=True, db_column="시설물분류(중)", null=True),
                ),
                (
                    "Facility_classification_small",
                    models.TextField(blank=True, db_column="시설물분류(소)", null=True),
                ),
                (
                    "Work_type_classification_Large",
                    models.TextField(blank=True, db_column="공종분류(대)", null=True),
                ),
                (
                    "Construction_type_classification_middle",
                    models.TextField(blank=True, db_column="공종분류(중)", null=True),
                ),
                (
                    "Classification_of_hazardous_objects_Large",
                    models.TextField(blank=True, db_column="위험발생객체분류(대)", null=True),
                ),
                (
                    "Classification_of_hazardous_objects",
                    models.TextField(blank=True, db_column="위험발생객체분류(중)", null=True),
                ),
                (
                    "Hazardous_location_classification_large",
                    models.TextField(blank=True, db_column="위험발생위치분류(대)", null=True),
                ),
                (
                    "Danger_occurrence_location_code_middle",
                    models.FloatField(blank=True, db_column="위험발생위치코드(중)", null=True),
                ),
                (
                    "Hazardous_location_classification_medium",
                    models.TextField(blank=True, db_column="위험발생위치분류(중)", null=True),
                ),
                (
                    "Hazardous_location_classification_small",
                    models.TextField(blank=True, db_column="위험발생위치분류(소)", null=True),
                ),
                (
                    "work_process",
                    models.TextField(blank=True, db_column="작업프로세스명", null=True),
                ),
                (
                    "blood_red_blood",
                    models.TextField(blank=True, db_column="물적피해", null=True),
                ),
                (
                    "human_blood",
                    models.TextField(blank=True, db_column="인적피해", null=True),
                ),
                (
                    "accident_center",
                    models.TextField(blank=True, db_column="사고원인", null=True),
                ),
                (
                    "Accident_possible",
                    models.TextField(blank=True, db_column="사고가능성", null=True),
                ),
                (
                    "Serious_accident",
                    models.TextField(blank=True, db_column="사고심각성", null=True),
                ),
                (
                    "design_team",
                    models.TextField(blank=True, db_column="설계단계", null=True),
                ),
                (
                    "Construction_team",
                    models.TextField(blank=True, db_column="시공단계", null=True),
                ),
            ],
            options={
                "db_table": "HazardProfile",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Riskfactorsprofile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Facility_classification_large",
                    models.TextField(blank=True, db_column="시설물분류_대", null=True),
                ),
                (
                    "Facility_classification_medium",
                    models.TextField(blank=True, db_column="시설물분류_중", null=True),
                ),
                (
                    "Facility_classification_small",
                    models.TextField(blank=True, db_column="시설물분류_소", null=True),
                ),
                (
                    "Construction_type_classification_Large",
                    models.TextField(blank=True, db_column="공종분류_대", null=True),
                ),
                (
                    "Construction_type_classification_middle",
                    models.TextField(blank=True, db_column="공종분류_중", null=True),
                ),
                (
                    "Risk_generating_object_Large",
                    models.TextField(blank=True, db_column="위험발생객체_대", null=True),
                ),
                (
                    "Dangerous_object_medium",
                    models.TextField(blank=True, db_column="위험발생객체_중", null=True),
                ),
                (
                    "Danger_occurrence_location_large",
                    models.TextField(blank=True, db_column="위험발생위치_대", null=True),
                ),
                (
                    "Danger_occurrence_location_middle",
                    models.TextField(blank=True, db_column="위험발생위치_중", null=True),
                ),
                (
                    "Location_of_risk_small",
                    models.TextField(blank=True, db_column="위험발생위치_소", null=True),
                ),
                (
                    "work_process",
                    models.TextField(blank=True, db_column="작업프로세스", null=True),
                ),
                (
                    "material_damage",
                    models.TextField(blank=True, db_column="물적피해", null=True),
                ),
                (
                    "human_damage",
                    models.TextField(blank=True, db_column="인적피해", null=True),
                ),
                (
                    "Accident_cause_code",
                    models.TextField(blank=True, db_column="사고원인코드", null=True),
                ),
                (
                    "possibility_of_accident",
                    models.TextField(blank=True, db_column="사고가능성", null=True),
                ),
                (
                    "Accident_severity",
                    models.TextField(blank=True, db_column="사고심각성", null=True),
                ),
                (
                    "Reduction_measures_design",
                    models.TextField(blank=True, db_column="저감대책_설계", null=True),
                ),
                (
                    "Reduction_measures_construction",
                    models.TextField(blank=True, db_column="저감대책_시공", null=True),
                ),
            ],
            options={
                "db_table": "RiskFactorsProfile",
                "managed": False,
            },
        ),
    ]
