# Generated by Django 5.0 on 2024-01-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adul", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BomAssemlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item",
                    models.CharField(
                        blank=True, db_column="Item", max_length=200, null=True
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, db_column="Title", max_length=50, null=True
                    ),
                ),
                (
                    "matl",
                    models.CharField(
                        blank=True, db_column="Matl", max_length=200, null=True
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, db_column="Description", max_length=200, null=True
                    ),
                ),
                (
                    "length",
                    models.IntegerField(blank=True, db_column="Length", null=True),
                ),
                ("qty", models.IntegerField(blank=True, db_column="Qty", null=True)),
                (
                    "weight",
                    models.IntegerField(blank=True, db_column="Weight", null=True),
                ),
                (
                    "paint",
                    models.IntegerField(blank=True, db_column="Paint", null=True),
                ),
            ],
            options={
                "db_table": "bom_assemlist",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BomList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assmark",
                    models.CharField(
                        blank=True, db_column="AssMark", max_length=200, null=True
                    ),
                ),
                (
                    "partmark",
                    models.CharField(
                        blank=True, db_column="PartMark", max_length=50, null=True
                    ),
                ),
                (
                    "h",
                    models.CharField(
                        blank=True, db_column="H", max_length=200, null=True
                    ),
                ),
                (
                    "b",
                    models.CharField(
                        blank=True, db_column="B", max_length=200, null=True
                    ),
                ),
                ("t1", models.CharField(blank=True, max_length=50, null=True)),
                ("t2", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "length",
                    models.IntegerField(blank=True, db_column="Length", null=True),
                ),
                ("qty", models.IntegerField(blank=True, db_column="Qty", null=True)),
                ("unit", models.IntegerField(blank=True, db_column="Unit", null=True)),
                (
                    "grade",
                    models.CharField(
                        blank=True, db_column="Grade", max_length=50, null=True
                    ),
                ),
                ("area", models.IntegerField(blank=True, db_column="Area", null=True)),
                (
                    "weight",
                    models.IntegerField(blank=True, db_column="Weight", null=True),
                ),
            ],
            options={
                "db_table": "bom_list",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BomPartlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mark",
                    models.CharField(
                        blank=True, db_column="Mark", max_length=50, null=True
                    ),
                ),
                (
                    "profile",
                    models.CharField(
                        blank=True, db_column="Profile", max_length=50, null=True
                    ),
                ),
                (
                    "length",
                    models.IntegerField(blank=True, db_column="Length", null=True),
                ),
                ("qty", models.IntegerField(blank=True, db_column="Qty", null=True)),
                (
                    "grade",
                    models.CharField(
                        blank=True, db_column="Grade", max_length=50, null=True
                    ),
                ),
                ("area", models.IntegerField(blank=True, db_column="Area", null=True)),
                ("unit", models.IntegerField(blank=True, db_column="Unit", null=True)),
                (
                    "weight_1",
                    models.IntegerField(blank=True, db_column="Weight_1", null=True),
                ),
                (
                    "weight_2",
                    models.IntegerField(blank=True, db_column="Weight_2", null=True),
                ),
            ],
            options={
                "db_table": "bom_partlist",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BomPlatelist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mark",
                    models.CharField(
                        blank=True, db_column="Mark", max_length=50, null=True
                    ),
                ),
                (
                    "profile",
                    models.CharField(
                        blank=True, db_column="Profile", max_length=50, null=True
                    ),
                ),
                (
                    "width",
                    models.CharField(
                        blank=True, db_column="Width", max_length=50, null=True
                    ),
                ),
                (
                    "length",
                    models.IntegerField(blank=True, db_column="Length", null=True),
                ),
                ("qty", models.IntegerField(blank=True, db_column="Qty", null=True)),
                (
                    "grade",
                    models.CharField(
                        blank=True, db_column="Grade", max_length=50, null=True
                    ),
                ),
                ("area", models.IntegerField(blank=True, db_column="Area", null=True)),
                (
                    "weight_1",
                    models.IntegerField(blank=True, db_column="Weight_1", null=True),
                ),
                (
                    "weight_2",
                    models.IntegerField(blank=True, db_column="Weight_2", null=True),
                ),
            ],
            options={
                "db_table": "bom_platelist",
                "managed": False,
            },
        ),
    ]
